export const UserActionTypes={
    FETCH_LOGIN:'FETCH_LOGIN',
    SET_LOGIN_STATUS:'SET_LOGIN_STATUS',
    LOGIN_FAIL:'LOGIN_FAIL',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    SET_USER_DETAILS:"SET_USER_DETAILS",
    SET_LOGIN_TOKEN:'SET_LOGIN_TOKEN',
    SET_TOKEN_STATUS:'SET_TOKEN_STATUS',
    RESET_USER:'RESET_USER',
    SET_REMEMBER_ME:'SET_REMEMBER_ME',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_ENV: 'SET_ENV',
    SAVE_PRINTER_IP:'SAVE_PRINTER_IP'
}