export const successModalTypes={
    MODAL_SET_SUCCESS_DATA:"MODAL_SET_SUCCESS_DATA",
    TOGGLE_SUCCESS_MODAL:"TOGGLE_SUCCESS_MODAL",
    SET_SUCCESS:'SET_SUCCESS',
    UNSET_SUCCESS:"UNSET_SUCCESS"
    
}