export const purchaseOrderTypes={
    STORE_RECENT_PURCHASE_ORDER : 'STORE_RECENT_PURCHASE_ORDER',
    SET_FETCHING_STATUS: 'SET_FETCHING_STATUS',
    SET_SALES_ORDER: 'SET_SALES_ORDER',
    SET_TOTALS_ARRAY: 'SET_TOTALS_ARRAY',
    SHOW_WO: 'SHOW_WO'
}