export const installationTypes={
    // STORE_PURCHASE_ORDER_ITEMS_SUCCESS:'STORE_PURCHASE_ORDER_ITEMS_SUCCESS',
    // FETCH_PURCHASE_ORDER_ITEMS_FAIL:'FETCH_PURCHASE_ORDER_ITEMS_FAIL',
    // CLEAR_PURCHASE_ORDER_ITEMS:'CLEAR_PURCHASE_ORDER_ITEMS',
    // CLEAR_PURCHASE_ORDER_STATUS:'CLEAR_PURCHASE_ORDER_STATUS',
    // UPDATE_PURCHASE_ORDER:'UPDATE_PURCHASE_ORDER',
    // SET_API_PO_LIST:'SET_API_PO_LIST',
    // CLEAR_UPDATED_PURCHASE_ORDER:'CLEAR_UPDATED_PURCHASE_ORDER',
    // CHANGE_UPDATE_PURCHASE_ORDER_API_STATUS:'CHANGE_UPDATE_PURCHASE_ORDER_API_STATUS'
    STORE_ITEMS_WITH_IMAGE_LIST:'STORE_ITEMS_WITH_IMAGE_LIST',
    CLEAR_ITEMS_WITH_IMAGE_LIST:'CLEAR_ITEMS_WITH_IMAGE_LIST',
    STORE_LIST_KEYS:'STORE_LIST_KEYS',
    CLEAR_LIST_KEYS:'CLEAR_LIST_KEYS',
    STORE_IMAGES:"STORE_IMAGES",
    CLEAR_IMAGES:'CLEAR_IMAGES',
    STORE_SELECTED_ITEMS:'STORE_SELECTED_ITEMS'
}